# Generated by Django 4.0.3 on 2022-04-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_image_productattribute_image'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='productattribute',
            index_together={('product', 'color', 'size')},
        ),
    ]
