# Generated by Django 4.0.3 on 2022-04-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_productattribute_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='productattribute',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'color', 'size')},
        ),
    ]
